USE SENATUR_MANHA

SELECT * FROM USUARIOS

SELECT * FROM USUARIOS WHERE EMAIL='ADMIN@ADMIN.COM' AND SENHA='ADMIN'

SELECT * FROM PACOTES

SELECT * FROM PACOTES WHERE PACOTEID='3'

UPDATE PACOTES SET VALOR = '1900' WHERE PACOTEID = 3