Create database SENATUR_MANHA
USE SENATUR_MANHA

CREATE TABLE PACOTES(
PACOTEID INT IDENTITY PRIMARY KEY	
,NOMEPACOTE VARCHAR(200) NOT NULL
,DESCRICAO VARCHAR(500) NOT NULL
,DATAIDA DATETIME NOT NULL
,DATAVOLTA DATETIME NOT NULL
,VALOR DECIMAL(10,2) NOT NULL	
,ATIVO VARCHAR(50) NOT NULL	
,NOMECIDADE VARCHAR(100)
);


CREATE TABLE USUARIOS(
USUARIOID INT IDENTITY PRIMARY KEY
,EMAIL VARCHAR(80) UNIQUE NOT NULL
,SENHA VARCHAR(100) NOT NULL
, TIPOUSUARIO VARCHAR(50) NOT NULL
);
